FROM node:20-alpine
WORKDIR /web
COPY package.json pnpm-lock.yaml* package-lock.json* yarn.lock* /web/
RUN if [ -f package-lock.json ]; then npm ci; \
    elif [ -f pnpm-lock.yaml ]; then npm i -g pnpm && pnpm i; \
    elif [ -f yarn.lock ]; then yarn install --frozen-lockfile; \
    else npm i; fi
COPY . /web
CMD ["npm","run","dev","--","--host","0.0.0.0"]
