# apps/api/app/tasks/chartprep.py
from __future__ import annotations
import datetime as dt, base64, logging
from typing import Optional, List
from sqlalchemy import text
from app.celery_app import celery_app
from app.db import SessionLocal

log = logging.getLogger(__name__)

def _data_url(html: str) -> str:
    return "data:text/html;base64," + base64.b64encode(html.encode("utf-8")).decode("ascii")

@celery_app.task(name="chartprep.run", acks_late=True)
def run(appointment_id: Optional[int] = None) -> dict:
    """
    If appointment_id is provided, generate a one-page Prechart for that appointment.
    Insert into documents(kind='Prechart') with JSON meta:
      { appointment_id, status: 'READY', generated_at }  (NOTE: meta is JSON, not JSONB)
    """
    db = SessionLocal()
    created_for: List[int] = []
    try:
        if appointment_id is not None:
            rows = db.execute(
                text("""
                    SELECT id, reason, start_at, fhir_appointment_id
                    FROM appointments
                    WHERE id = :aid
                """),
                {"aid": int(appointment_id)},
            ).mappings().all()
        else:
            today = dt.datetime.utcnow().date()
            start = dt.datetime.combine(today + dt.timedelta(days=1), dt.time(0, 0))
            end   = start + dt.timedelta(days=1)
            rows = db.execute(
                text("""
                    SELECT id, reason, start_at, fhir_appointment_id
                    FROM appointments
                    WHERE start_at >= :start AND start_at < :end
                    ORDER BY id
                """),
                {"start": start, "end": end},
            ).mappings().all()

        for appt in rows:
            appt_id = int(appt["id"])
            created_for.append(appt_id)

            html = f"""<!doctype html>
<html>
<head><meta charset="utf-8"><title>Prechart #{appt_id}</title></head>
<body style="font-family:system-ui,Segoe UI,Arial,sans-serif">
  <h1>Prechart – Appointment #{appt_id}</h1>
  <ul>
    <li><b>Reason:</b> {appt.get("reason") or "-"}</li>
    <li><b>Start:</b> {appt.get("start_at")}</li>
    <li><b>FHIR Appointment:</b> {appt.get("fhir_appointment_id")}</li>
  </ul>
  <p>This prechart was generated by chartprep.run.</p>
</body></html>"""

            url = _data_url(html)

            # IMPORTANT: meta is JSON (not JSONB). Build with jsonb_build_object then cast back to JSON.
            db.execute(
                text("""
                    INSERT INTO documents(kind, url, meta)
                    VALUES (
                      'Prechart',
                      :url,
                      (jsonb_build_object(
                        'appointment_id', :aid,
                        'status', 'READY',
                        'generated_at', NOW()
                      ))::json
                    )
                """),
                {"url": url, "aid": appt_id},
            )

        db.commit()
        return {"created": len(created_for), "appointments": created_for}
    except Exception:
        db.rollback()
        raise
    finally:
        db.close()
